[package]
name = "send_file"
version = "0.1.0"
authors = ["EelenZ <3143157934@qq.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async-std = {version = "1.6.4",  features = ["attributes"] }
uuid = { version = "0.8", features = ["serde", "v4"] }
futures = "0.3.5"
